FROM node:20-alpine AS build
WORKDIR /frontend

COPY package.json /frontend/package.json
RUN npm install

COPY . /frontend
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80
